### ISSUE TITLE
ipv6SRHFlags subregistry is empty

### ISSUE THREAD

**Issue by bclaise** [graf3net/draft-tgraf-opsawg-ipfix-srv6-srh#3]
Hi,

We should discuss the need to create a subregistry with no values.

Regards, B.

**Comment by bclaise** [comment]
I don't think the following IANA process is right:
4.1.  ipv6SRHFlags

   Name: ipv6SRHFlags
   ElementID: TBD1
   Description: This Information Element identifies the 8-bit flags
   defined in the SRH.  Values for this Information Element are listed
   in the "IPFIX IPv6 SRH Flags" registry, see [IANA-IPFIX].  Initial
   values in the registry are defined by the table below.  New
   assignments of values will be administered by IANA and are subject to
   Expert Review [RFC8126].  Experts need to check definitions of new
   values for completeness, accuracy, and redundancy.

I mean... I understand that "Segment Routing Header Flags" at https://www.iana.org/assignments/ipv6-parameters/ipv6-parameters.xhtml#segment-routing-header-flags is currently empty. Having IPFIX experts go through a review of IPFIX IE definition from an IPFIX spec. point of view for the first entry makes sense, but after that, the mapping of "https://www.iana.org/assignments/ipv6-parameters/ipv6-parameters.xhtml#segment-routing-header-flags" to the "IPFIX IPv6 SRH Flags" should be automatic, without expert review

Similar example: https://www.iana.org/assignments/iana-if-type/iana-if-type.xhtml
I could discuss with IANA on the proper wording during the IETF.

**Comment by bclaise** [comment]
Well, https://www.iana.org/assignments/ipv6-parameters/ipv6-parameters.xhtml#segment-routing-header-flags is not empty any longer. This is actually good news. 

I propose to update the draft with this text below. From there, we could ping IANA.

OLD:

4.1.  srhFlagsIPv6

   Name: srhFlagsIPv6
   ElementID: TBD1
   Description: This Information Element identifies the 8-bit flags
   defined in the SRH.  Values for this Information Element are listed
   in the "IPFIX IPv6 SRH Flags" registry, see [IANA-IPFIX].  Initial
   values in the registry are defined by the table below.  New
   assignments of values will be administered by IANA and are subject to
   Expert Review [RFC8126].  Experts need to check definitions of new
   values for completeness, accuracy, and redundancy.

   +--------+-------------------+--------------------------------------+
   | Valu  |    Description  |              Reference                   |
   +--------+-------------------+--------------------------------------+
   | 0-7    | Unassigne      |                                                    |
   +--------+-------------------+--------------------------------------+

         Table 2: "IPFIX IPv6 SRH Flags" registry

   Abstract Data Type: unsigned8
   Data Type Semantics: flags
   Reference: [RFC-to-be], RFC8754

NEW:
4.1.  srhFlagsIPv6

   Name: srhFlagsIPv6
   ElementID: TBD1
   Description: This Information Element identifies the 8-bit flags
   defined in the SRH.  Values for this Information Element are listed
   in the "IPFIX IPv6 SRH Flags" registry, see [IANA-IPFIX].  
   srhFlagsIPv6 values must not be directly added to this "IPFIX
   IPv6 SRH Flags" registry. They must instead be added to the
   "Segment Routing Header Flags" registry. Both the the "IPFIX IPv6
   SRH Flags" and "Segment Routing Header Flags" registries must be
   kept in synch.
   Initial values in the registry are defined by the table below.

   +--------+-------------------+--------------------------------------+
   | Value |   Description |              Reference                   |
   +--------+-------------------+--------------------------------------+
   | 0-1    | Unassigned     |                                                   |
   +--------+-------------------+--------------------------------------+
   |   2      | O-flag              |[[RFC-ietf-6man-spring-srv6-oam-13](https://www.iana.org/go/draft-ietf-6man-spring-srv6-oam-13)]|
   +--------+-------------------+--------------------------------------+
   | 3-7    | Unassigned     |                                                   |
   +--------+-------------------+--------------------------------------+

         Table 2: "IPFIX IPv6 SRH Flags" registry

   Abstract Data Type: unsigned8
   Data Type Semantics: flags
   Reference: [RFC-to-be], RFC8754

**Comment by graf3net** [comment]
Hi Benoit, thanks a lot. Has been merged in latest -04 release
