### ISSUE TITLE
Align the IPFIX IE names with the IANA registry? 

### ISSUE THREAD

**Issue by bclaise** [graf3net/draft-tgraf-opsawg-ipfix-srv6-srh#5]
One comment, for discussion. I wonder whether the 
[4.3](https://datatracker.ietf.org/doc/html/draft-tgraf-opsawg-ipfix-srv6-srh-02#section-4.3).  ipv6SRHSegment

   Name: ipv6SRHSegment ElementID: TBD3 Description: This Information
   Element identifies the 128-bit IPv6 address that represents an SRv6
   segment.  Abstract Data Type: ipv6address Data Type Semantics:
   default Reference: [RFC-to-be], [RFC8754](https://datatracker.ietf.org/doc/html/rfc8754)

Should not be called called ipv6SRHTopSegment, to make the link with MPLS Labels IPFIX IEs. 

See https://www.iana.org/assignments/ipfix/ipfix.xhtml

Thinking about naming convenient, most IPFIX IEs have "IPv6" at the end of their names
So SRHTopSegmentIPv6?
We might have to change all the IPFIX names in the end.

**Comment by bclaise** [comment]
Re-reading https://datatracker.ietf.org/doc/html/rfc7013#section-4.1...
   o  start with lowercase letters.
And looking at mpls* IEs, as opposed to MPLS* ...
I believe we need to start our IEs with "sr".
So 
IPv6SRHFlags => srhFlagsIPv6
IPv6SRHTag => srhTagIPv6
IPv6SRHSegment => srhTopSegmentIPv6
IPv6SRHSegmentListSection => srhSegmentListSectionIPv6
IPv6SRHSegmentsLeft => srhSegmentsLeftIPv6
IPv6SRHSection => srhSectionIPv6
IPv6SRHSegmentType => srhSegmentTypeIPv6

**Comment by graf3net** [comment]
addressed with commit [8b4e3397ccdb262b7dc35c596c190f254813e8ea](https://github.com/graf3net/draft-tgraf-opsawg-ipfix-srv6-srh/commit/8b4e3397ccdb262b7dc35c596c190f254813e8ea)
