### ISSUE TITLE
Compressed SRv6 SID

### ISSUE THREAD

**Issue by bclaise** [graf3net/draft-tgraf-opsawg-ipfix-srv6-srh#6]
I believe we want to say a few words about compressed SRv6 SID.
Personally, I still have to review https://datatracker.ietf.org/doc/draft-ietf-spring-srv6-srh-compression/ but I believe it's worth discussing the following:

As described in https://datatracker.ietf.org/doc/html/draft-ietf-spring-srv6-srh-compression-00.html#section-2, the compressed-SID container (C-SID container) is 128-bit long and contains a sequence of C-SIDs. Therefore the ipv6SRHSegmentList

contains either a list of IPv6 SID's, a list of compressed-SID containers or both. They are not mutually exclusive.

It probably makes sense to add an operational consideration section in draft-tgraf-opsawg-ipfix-srv6-srh to describe the use of C-SID containers and its context to ipv6SRHSegmentType. From what I understood, and here I would like to have feedback from the mailing list, it does not bring much added value to decompose the C-SID container into Compressed-SID (C-SID) in IPFIX.

The question in my mind is how would a collector make the distinction between C-SID or not from a IPFIX IE point of view, if reported by the same IE?
I agree that some text in the "operational considerations" would help (me)d help (me)

**Comment by graf3net** [comment]
addressed
